### ISSUE TITLE
请一下，可以在国内开个吗

### ISSUE THREAD

**Issue by zjralhf** [wxxxcxx/azure-tts-lexicon-cn#1]
国内网络经常访问不了github，希望可以在国内弄个这样访问方便点。

**Comment by wxxxcxx** [comment]
~~使用 Azure TTS 只需要提供 lexicon.xml 文件的链接，这个文件是由微软服务器去访问的。So 放在 Github 应该不存在什么无法访问的问题。~~

可能是我误解你的意思了？你是希望仓库放在国内的代码托管平台吗？听说要审核好像挺麻烦的～所以暂时没弄😂

**Comment by zjralhf** [comment]
谢谢你的回复，我其实是你上面那个意思，我用docker弄好，很方便，想试试多音字的处理。
